### ISSUE TITLE
<Link> Does not work on build

### ISSUE THREAD

**Issue by glowtoad123** [saltyshiomix/nextron#95] opened 2020-08-19 13:23 UTC
Everytime I build the app I cannot navigate between pages. This even happened on the boilerplate. However, when I run on dev if works perfectly fine.

**Comment by eduardocp** [comment] 2020-08-20 00:12
> Everytime I build the app I cannot navigate between pages. This even happened on the boilerplate. However, when I run on dev if works perfectly fine.

Are you using the latest version of nextjs?
Can you show your package.json?

**Comment by glowtoad123** [comment] 2020-08-20 00:47
Thanks for responding. I believe I'm using version 9.4.4 of Nextjs. [package.json](https://github.com/glowtoad123/codentake_nextron/blob/master/package.json)

**Comment by guicostaarantes** [comment] 2020-08-20 02:05
Same happening here, Mac OS 10.15.5
`yarn create-nextron-app example --example with-typescript`
`cd example`
`yarn`
`yarn dev`
Navigation works
`yarn build`
Double-click example/dist/mac/My Nextron App.app
Navigation does not work

**Comment by guicostaarantes** [comment] 2020-08-20 02:20
Also tested for Windows 10 2004, works on dev and does not work on build.

**Comment by eduardocp** [comment] 2020-08-20 03:16
> Also tested for Windows 10 2004, works on dev and does not work on build.

Same here, but in latest version of nextjs.
The redirect dont work with `useRouter()` too.

**Comment by lolieatapple** [comment] 2020-08-26 04:15
Same happening here, Mac OS 10.15.5
npx create-nextron-app my-app
cd my-app
yarn
yarn dev
Navigation works
yarn build
Double-click my-app/dist/mac/My Nextron App.app
Navigation does not work.

And I took a look of DevTools,in source page, I found there is no next.html file, only have home.html file.

I found both home.html and next.html in my-app/app directory. but it seems next.html not packed.

**Comment by devrnsistema** [comment] 2020-09-01 12:40
how do I be able to access the pages with the application and production, developing access normally by port 8888, but in production how do I do?

**Comment by eduardocp** [comment] 2020-09-01 12:57
> how do I be able to access the pages with the application and production, developing access normally by port 8888, but in production how do I do?

I believe there is no way. In development mode there is a separate server for the pages and the electron only accesses that url. When it is production it is electron itself that creates this server and it is only available within the application.

Someone correct me if I'm wrong please.

**Comment by saltyshiomix** [comment] 2020-09-05 08:11
I reproduced the error.
So I'll replace `electron-serve` for now.

**Comment by saltyshiomix** [comment] 2020-09-05 10:24
Next.js causes this error: (invariant: invalid relative URL)

https://github.com/vercel/next.js/blob/764b194505caf1e3f10e58f57b8a06eaecc8ca75/packages/next/next-server/lib/router/utils/parse-relative-url.ts#L29

Currently nextron registers `app` directory as a file protocol, but Next.js reject it.

**Comment by saltyshiomix** [comment] 2020-09-05 10:32
@glowtoad123 @eduardocp @guicostaarantes @lolieatapple @devrnsistema 

Because of the above, `next@9.3.6` should fix this issue.

Please try it :)

(Be careful, not `next@^9.3.6` but `next@9.3.6`)

**Comment by danikaze** [comment] 2020-09-05 13:32
Might be related to #96 ?
Maybe not, but asking...

**Comment by AhmedGamal1496** [comment] 2020-09-24 09:35
@saltyshiomix Hello, I changed `next@^9.3.6` to `next@9.3.6` but it produced multiple errors such as "Cannot find module "cacache" and cannot access renderer/.next/cache folder. 

`> Build error occurred
{ Error: Cannot find module 'cacache'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.635 (/home/jimy/Documents/mcit-fatclient/node_modules/next/dist/compiled/terser-webpack-plugin/cjs.js:1:15262)
    at __webpack_require__ (/home/jimy/Documents/mcit-fatclient/node_modules/next/dist/compiled/terser-webpack-plugin/cjs.js:1:154)
    at Object.314 (/home/jimy/Documents/mcit-fatclient/node_modules/next/dist/compiled/terser-webpack-plugin/cjs.js:1:7982)
    at __webpack_require__ (/home/jimy/Documents/mcit-fatclient/node_modules/next/dist/compiled/terser-webpack-plugin/cjs.js:1:154)
    at TerserPlugin.o (/home/jimy/Documents/mcit-fatclient/node_modules/next/dist/compiled/terser-webpack-plugin/cjs.js:1:6462)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/jimy/Documents/mcit-fatclient/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:17) code: 'MODULE_NOT_FOUND' }
Creating an optimized production build .> using build directory: /home/jimy/Documents/mcit-fatclient/renderer/.next
{ Error: ENOENT: no such file or directory, open '/home/jimy/Documents/mcit-fatclient/renderer/.next/BUILD_ID'
    at Object.openSync (fs.js:443:3)
    at readFileSync (fs.js:343:35)
    at _default (/home/jimy/Documents/mcit-fatclient/node_modules/next/dist/export/index.js:1:3652)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path:
   '/home/jimy/Documents/mcit-fatclient/renderer/.next/BUILD_ID' }`

`Cannot build electron packages:
Error: ENOENT: no such file or directory, stat '/home/jimy/Documents/mcit-fatclient/renderer/out'`

**Comment by saltyshiomix** [comment] 2020-09-25 01:58
@AhmedGamal1496 
Thank you for your reporting the issue!

I figured it out this is because nextron hard-codes `.next` dist directory and the `out` export directory.

https://github.com/saltyshiomix/nextron/blob/master/lib/nextron-build.ts#L71-L74

**Comment by saltyshiomix** [comment] 2020-09-25 02:13
@AhmedGamal1496 

Just released `nextron@5.15.2`, could you try this one?

**Comment by AhmedGamal1496** [comment] 2020-09-27 08:36
@saltyshiomix 
I have tried `nextron@5.15.2`. It worked just fine for the `.next` dist directory problem, but there are problems with `next` version. I have to downgrade to `next@9.3.5` to solve the error which I posted above and the navigation problem.

But everything is fine on my side until now. If you need me to try anything else, please let me know.

**Comment by saltyshiomix** [comment] 2020-09-29 04:29
@AhmedGamal1496 

Thank you for your kindness.

I'll try to fix the next version problem as soon as possible.

**Comment by hirotachi** [comment] 2020-09-29 11:36
By the way I had the same issue with links not working on production, currently the only version they're working on is next@9.5.1

**Comment by saltyshiomix** [comment] 2020-10-18 00:02
Nextron v5.15.3 is out :)

**Comment by Kosai106** [comment] 2020-11-11 22:30
The issue is still present in version `5.15.7`. The only fix I found was to roll back from Next.js 10 to `9.5.1`

**Comment by hirotachi** [comment] 2020-11-14 00:25
@saltyshiomix @Kosai106 
the issue will be fixed on the upcoming nextjs version 10.0.2 it is already merged https://github.com/vercel/next.js/pull/16650
I currently switched to next@canary and all is good now

**Comment by conquera99** [comment] 2020-11-19 08:28
[Next.js 10.0.0.2](https://github.com/vercel/next.js/releases/tag/v10.0.2) is released,
it works now

**Comment by saltyshiomix** [comment] 2020-11-21 08:47
I'll prepare(nextron@6)

**Comment by saltyshiomix** [comment] 2020-11-29 06:53
Just released nextron v6 🎉 

This issue will be closed within a few week :)

CC: @glowtoad123 @eduardocp @guicostaarantes @lolieatapple @devrnsistema @AhmedGamal1496 @Kosai106 @hirotachi @conquera99

**Comment by mrgoonie** [comment] 2020-11-29 07:37
You rocks @saltyshiomix ! 🚀 🚀 🚀

**Comment by saltyshiomix** [comment] 2021-01-16 06:59
It seems to be fixed :)

**Closed by saltyshiomix** 2021-01-16 06:59 UTC
Labels: good first issue

**Comment by v1b3m** [comment] 2022-01-09 14:20
Hey,
I'm running `"nextron": "^7.1.0"` and `"next": "11.1.2"`, development app works fine, routes and everything, but the production build just won't do any routing. Stuck on `index.html`
