### ISSUE TITLE
Change port next

### ISSUE THREAD

**Issue by PonorogoCreativeIT** [saltyshiomix/nextron#12] opened 2018-10-10 14:16 UTC
how i can change port default from 8888 to another port?

thank you

**Comment by saltyshiomix** [comment] 2018-10-11 13:57
Hi, @PonorogoCreativeIT !

Sorry currently it won't be changeable.
It will be changeable `nextron@3` I planned.

**Comment by saltyshiomix** [comment] 2018-10-16 14:41
Just released `nextron@3`!
Since v3, you can change port manually both in main process and renderer process :)

**Comment by bkniffler** [comment] 2019-10-09 09:36
But how do we actually change the port?  Can't find any docs :(

**Comment by saltyshiomix** [comment] 2019-10-09 13:15
@bkniffler 

Sorry there is a regression because I thought that there is no need to change the development port for the purpose of these points:

- In production build,
  - Nextron uses the command `next export renderer` so the port will won't appear
  - We can't use nodejs ports for the security reasons (that is, we can handle only static files in electron)

But it is inconvenient if we use the port `8888` in another projects, so I'll implement it in the next release of nextron 👍 (probablly in the `nextron.config.js` I think)

**Comment by bkniffler** [comment] 2019-10-09 13:49
Could you maybe allow for -p arg? Thats the easiest and it is conforming to nextjs. Cheers!

**Comment by saltyshiomix** [comment] 2019-10-09 13:54
@bkniffler 

Yesyesyes I fogot that! lol

I'll add `nextron (dev) -p XXXX` later today.

**Comment by saltyshiomix** [comment] 2019-10-09 16:18
@bkniffler 
@PonorogoCreativeIT 

`nextron@5.12.0` is out 👍 

```bash
$ npm i -g nextron

# see the example of custom port :)
$ nextron init test-app --example custom-renderer-port
$ cd test-app
$ npm install && npm run dev
```

**Comment by saltyshiomix** [comment] 2019-10-10 01:48
Supported, so I closed this issue :)

**Closed by saltyshiomix** 2019-10-10 01:48 UTC
Labels: enhancement
