### ISSUE TITLE
build error when I install firebase

### ISSUE THREAD

**Issue by obscure12** [saltyshiomix/nextron#62] opened 2019-11-26 21:03 UTC
I created project by this command.

```
npx create-nextron-app <MY-APP> --example with-typescript-material-ui
```

and run `npm run build`
This time I finished this command successfully.

But after I installed firebase by this command.

```
npm install --save firebase
```

and I run `npm run build` again

there are these error

```
rebuilding native dependencies  dependencies=grpc@1.24.2 platform=darwin arch=x64
Failed at the grpc@1.24.2 install script.
```
Please kindly check. Thank you

**Comment by lacymorrow** [comment] 2019-11-26 23:12
Hi @obscure12, what version of NodeJS are you running?

**Comment by obscure12** [comment] 2019-11-26 23:47
Hi @lacymorrow 

this is my environment

```
node 
v12.13.1

npm
6.12.1
```

**Comment by saltyshiomix** [comment] 2019-12-10 11:19
@obscure12 

Sorry I can't reproduce the error:

(Building is successful)

<img width="670" alt="スクリーンショット 2019-12-10 20 16 54" src="https://user-images.githubusercontent.com/5608079/70525195-23e70180-1b8a-11ea-927b-7b9dc0994844.png">

But it takes about 10 minutes.

It may be the network or out of memory error, I wonder.

**Comment by obscure12** [comment] 2019-12-10 11:24
@saltyshiomix 
Thank you so much for your response.
Could you tell me your environment and process of creating project

What are your **node** , **npm** and nextron version ?

and is this same process with you ?

```
npx create-nextron-app example-project --example with-typescript-material-ui

npm install --save firebase

npm run build
```

Please kindly check. Thank you

**Comment by saltyshiomix** [comment] 2019-12-10 12:21
@obscure12 

Here is my env:

- Node.js `v12.13.1`
- npm `v6.12.1`
- nextron `v5.14.0`

And surely I tracked the same instructions 👍

**Comment by saltyshiomix** [comment] 2019-12-10 12:31
https://github.com/grpc/grpc-node/issues/888

**Comment by saltyshiomix** [comment] 2019-12-10 12:53
@obscure12 

Do you use `nvm` for Node.js version management?

I use Node.js from homebrew:

```zsh
$ brew install node@12
```

**Comment by obscure12** [comment] 2019-12-11 00:25
@saltyshiomix 
I'm using nodebrew

**Comment by Psycokwet** [comment] 2023-05-07 13:04
This is pretty old, and have been abandoned for a while, closing it now to tidy up a bit 😄

**Closed by Psycokwet** 2023-05-07 13:04 UTC
